### ISSUE TITLE
Don't see photos of people in my conversations

### ISSUE THREAD

**Issue by hedayat** [sialan-labs/sigram#71] opened 2014-08-15 10:27 UTC
Hi,
I've a number of contacts (well, I've never added anyone as contacts but I have conversations with them so they appear in the left pane), but their photoes are not being shown. I only see the photo of a single group I'm member of. But I'm able to see their photoes in other clients (e.g. tdesktop which can be considered a competitor for sigram now).

**Comment by Choochmeque** [comment] 2014-08-15 14:41
Can you please check this issue with my fork? Hope, i fixed it.

**Comment by hedayat** [comment] 2014-08-15 21:10
Tried your fork. I can see my own photo, but not my peers!

**Comment by Choochmeque** [comment] 2014-08-16 07:32
Is there any avatars in folder ~/.config/sialan/telegram/downloads?

**Comment by hedayat** [comment] 2014-08-16 07:34
Yes, mine and the avatar of the group that I mentioned. Nothing else.

**Comment by Choochmeque** [comment] 2014-08-16 07:55
I think, the main reason in this "I've never added anyone as contacts but I have conversations with them", because

telegramthread.cpp

<code>
void TelegramThread::loadUserInfo(int userId)
{
    if( !p->contacts.contains(userId) ) <--- this line doesn't allow get user information for non-added contacts
        return;
</code>

I don't know is it by design or not lol =)

**Comment by realbardia** [comment] 2014-08-16 08:02
It's beacuse telegram-cli limits...
We are porting sigram to libqtelegram wich is better than telegram-cli.
But I'll try to fix it on our master branch soon.

**Comment by hedayat** [comment] 2014-08-16 08:08
Thanks. It's unfortunate that there is no proper C/C++ API for Telegram. BTW, are you sure that libqtelegram doesn't have such problems? They have started from telegram-cli too, I wonder if they have filled the missing parts.

**Comment by realbardia** [comment] 2014-11-23 21:25
Fixed on Sigram-One branch.
Sigram One is next sigram, based on libqtelegram and completely rewriten.
It will release soon :)

**Closed as completed by realbardia** 2014-11-23 21:25 UTC
Labels: bug
